export { default as Hello } from './1Hello'
export { default as Hero } from './2Hero'
export { default as Features } from './3Features'
export { default as CTA } from './4CTA'
export { default as Testimonials } from './5Testimonials'
export { default as ThreeColumns } from './6ThreeColumns'
export { default as Contact } from './7Contact'